# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_de_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    #
    # STYLES
    #
    styleLineEditOk = ("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color:rgb(61, 61, 61);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(252,204,16);\n"
"    color: rgb(200, 200, 200);\n"
"}")

    styleLineEditError = ("QLineEdit {\n"
"    border: 2px solid rgb(186, 72, 37);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color:rgb(61, 61, 61);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(252,204,16);\n"
"    color: rgb(200, 200, 200);\n"
"}")

    stylePopupError = ("background-color: rgb(186, 72, 37); border-radius: 5px;")
    stylePopupOk = ("background-color: rgb(255, 216, 16); border-radius: 5px;")


    #
    # FUNCOES
    #

    def checkFields(self):
        textUser = ""
        textPass = ""

        def showMessage(message):
            self.frame_error.show()
            self.label_error.setText(message)


        # CHECK USER
        if not self.lineEdit_user.text():
            textUser = " User Empyt. "
            self.lineEdit_user.setStyleSheet(self.styleLineEditError)

        else:
            textUser = ""
            self.lineEdit_user.setStyleSheet(self.styleLineEditOk)

        # CHECK PASSWORD
        if not self.lineEdit_pass.text():
            textPass = " Password Empyt. "
            self.lineEdit_pass.setStyleSheet(self.styleLineEditError)
        else:
            textPass = ""
            self.lineEdit_pass.setStyleSheet(self.styleLineEditOk)

        # CHECK FIELDS
        if textUser + textPass != "":
            text = textUser + textPass
            showMessage(text)
            self.frame_error.setStyleSheet(self.stylePopupError)
        else:
            text = " Conectado! "
            if self.checkBox_save_user.isChecked():
                text = text + " | Usuário salvo! "
            showMessage(text)
            self.frame_error.setStyleSheet(self.stylePopupOk)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 584)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/login_icone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("color: rgba(200, 200, 200, 200);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fundo = QtWidgets.QFrame(self.centralwidget)
        self.fundo.setMinimumSize(QtCore.QSize(500, 500))
        self.fundo.setStyleSheet("background-color: rgb(42, 42, 42);")
        self.fundo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo.setObjectName("fundo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fundo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top = QtWidgets.QFrame(self.fundo)
        self.top.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top.setStyleSheet("background-color: rgb(16, 16, 16);")
        self.top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top.setObjectName("top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top)
        self.horizontalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_error = QtWidgets.QFrame(self.top)
        self.frame_error.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_error.setStyleSheet(self.stylePopupOk)
        self.frame_error.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_error.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_error.setObjectName("frame_error")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_error)
        self.horizontalLayout_4.setContentsMargins(10, 3, 10, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_error = QtWidgets.QLabel(self.frame_error)
        self.label_error.setStyleSheet("color: rgb(35, 35, 35);")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.horizontalLayout_4.addWidget(self.label_error)
        self.pushButton_popup = QtWidgets.QPushButton(self.frame_error)
        self.pushButton_popup.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_popup.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    image: url(:/close_x/icone_X-removebg-preview.png);\n"
"    background-position: center;\n"
"    \n"
"    background-color: rgb(255, 204, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(141, 141, 141);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(200, 200, 200);\n"
"} ")
        self.pushButton_popup.setText("")
        self.pushButton_popup.setObjectName("pushButton_popup")
        self.horizontalLayout_4.addWidget(self.pushButton_popup)
        self.horizontalLayout_3.addWidget(self.frame_error)
        self.verticalLayout.addWidget(self.top)
        self.frame_3 = QtWidgets.QFrame(self.fundo)
        self.frame_3.setStyleSheet("background-color: rgb(16, 16, 16);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_area = QtWidgets.QFrame(self.frame_3)
        self.login_area.setMaximumSize(QtCore.QSize(400, 450))
        self.login_area.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"border-radius: 4px;")
        self.login_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.login_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_area.setObjectName("login_area")
        self.logo = QtWidgets.QFrame(self.login_area)
        self.logo.setGeometry(QtCore.QRect(20, 0, 360, 90))
        self.logo.setMinimumSize(QtCore.QSize(360, 90))
        self.logo.setMaximumSize(QtCore.QSize(0, 0))
        self.logo.setStyleSheet("background-image: url(:/logo_danyels/cyber_sem_converter.png);\n"
"background-position: center;")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.avatar = QtWidgets.QFrame(self.login_area)
        self.avatar.setGeometry(QtCore.QRect(125, 90, 150, 150))
        self.avatar.setStyleSheet("QFrame {\n"
"    background-image: url(:/Perfil/Chrollo-Lucilfer-Wallpaper-3.png);\n"
"    border-radius: 75px;\n"
"    border: 3px solid rgb(252,204,16)\n"
"}\n"
"QFrame:hover {\n"
"    border: 3px solid rgb(252,222,16)\n"
"}")
        self.avatar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.avatar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.avatar.setObjectName("avatar")
        self.lineEdit_user = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_user.setGeometry(QtCore.QRect(60, 250, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet(self.styleLineEditOk)
        self.lineEdit_user.setMaxLength(32)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lineEdit_pass = QtWidgets.QLineEdit(self.login_area)
        self.lineEdit_pass.setGeometry(QtCore.QRect(60, 305, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setStyleSheet(self.styleLineEditOk)
        self.lineEdit_pass.setMaxLength(16)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.checkBox_save_user = QtWidgets.QCheckBox(self.login_area)
        self.checkBox_save_user.setGeometry(QtCore.QRect(60, 360, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.checkBox_save_user.setFont(font)
        self.checkBox_save_user.setStyleSheet("QCheckBox::indicator {\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border: 3px solid rgb(255, 205, 0);\n"
"    background-color: rgb(255, 255, 0);\n"
"}")
        self.checkBox_save_user.setObjectName("checkBox_save_user")
        self.pushButton_connect = QtWidgets.QPushButton(self.login_area)
        self.pushButton_connect.setGeometry(QtCore.QRect(60, 385, 280, 35))
        self.pushButton_connect.setStyleSheet("QPushButton {\n"
"    background-color: rgb(62, 62, 62);\n"
"    border: 2px solid rgb(60, 60, 60);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(250, 230, 0);\n"
"    border: 2px solid rgb(252,204,16);\n"
"    border-radius: 5px;\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.horizontalLayout_2.addWidget(self.login_area)
        self.verticalLayout.addWidget(self.frame_3)
        self.down = QtWidgets.QFrame(self.fundo)
        self.down.setMinimumSize(QtCore.QSize(0, 0))
        self.down.setMaximumSize(QtCore.QSize(16777215, 35))
        self.down.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.down.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.down.setFrameShadow(QtWidgets.QFrame.Raised)
        self.down.setObjectName("down")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.down)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_credits = QtWidgets.QLabel(self.down)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("")
        self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_credits.setObjectName("label_credits")
        self.verticalLayout_2.addWidget(self.label_credits)
        self.verticalLayout.addWidget(self.down)
        self.horizontalLayout.addWidget(self.fundo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 21))
        self.menubar.setStyleSheet("background-color: rgb(16, 16, 16);")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        #
        # functions
        #

        # botão que fecha popup
        self.pushButton_popup.clicked.connect(lambda: self.frame_error.hide)

        # esconder barra de erro
        self.frame_error.hide()

        # BT CONNECT
        self.pushButton_connect.clicked.connect(self.checkFields)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_error.setText(_translate("MainWindow", "error"))
        self.lineEdit_user.setPlaceholderText(_translate("MainWindow", "USER"))
        self.lineEdit_pass.setPlaceholderText(_translate("MainWindow", "PASS"))
        self.checkBox_save_user.setText(_translate("MainWindow", "SAVE USER"))
        self.pushButton_connect.setText(_translate("MainWindow", "CONNECT"))
        self.label_credits.setText(_translate("MainWindow", "GitHub: CromaFall"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
